// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tony.Rooms.Storage;

#nullable disable

namespace Tony.Rooms.Migrations
{
    [DbContext(typeof(RoomStorage))]
    partial class RoomStorageModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Tony.Rooms.Storage.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("IsNode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_node");

                    b.Property<bool>("IsPublicSpace")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_public_space");

                    b.Property<bool>("IsTradingAllowed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_trading_allowed");

                    b.Property<int>("MinAccess")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_access");

                    b.Property<int>("MinAssign")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_assign");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("ParentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_id");

                    b.HasKey("Id");

                    b.ToTable("navigator_categories");
                });
#pragma warning restore 612, 618
        }
    }
}
