// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tony.Player.Storage;

#nullable disable

namespace Tony.Player.Migrations
{
    [DbContext(typeof(PlayerStorage))]
    partial class PlayerStorageModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Tony.Player.Storage.Entities.PlayerData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Credits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("credits");

                    b.Property<string>("Figure")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("figure");

                    b.Property<int>("Film")
                        .HasColumnType("INTEGER")
                        .HasColumnName("film");

                    b.Property<string>("Mission")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mission");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<string>("PoolFigure")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("pool_figure");

                    b.Property<bool>("ReceiveNews")
                        .HasColumnType("INTEGER")
                        .HasColumnName("receive_news");

                    b.Property<bool>("Sex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sex");

                    b.Property<int>("Tickets")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tickets");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("player_data");
                });
#pragma warning restore 612, 618
        }
    }
}
